{{- if and .Values.rbac.create (eq .Values.rbac.scope "Namespaced") }}
{{- $namespaces := .Values.rbac.watchNamespaces | default (list .Release.Namespace) }}
{{- $fullName := include "dso.fullname" . }}
{{- $labels := include "dso.labels" . }}
{{- range $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-manager-role
  namespace: {{ $ns }}
  labels:
    {{- $labels | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  {{- if $.Values.argoCD.autoPatch }}
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - patch
      - update
  {{- end }}
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cilium.io
    resources:
      - ciliumnetworkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dso.quantumsys.dev
    resources:
      - dynamicsecretpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dso.quantumsys.dev
    resources:
      - dynamicsecretpolicies/status
      - dynamicsecretpolicies/finalizers
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
{{- end }}
