{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dso.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dso.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.azure.workloadIdentity.enabled .Values.azure.workloadIdentity.clientId }}
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId | quote }}
    {{- if .Values.azure.workloadIdentity.tenantId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.workloadIdentity.tenantId | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
