{{- if .Values.serviceAccount.create -}}
{{- $isESO := eq .Values.mode "eso" -}}
{{- $isAzure := or (eq .Values.provider "azure") (and (not .Values.provider) (ne .Values.mode "eso")) -}}
{{- $azureWorkloadIdentityEnabled := and (not $isESO) $isAzure .Values.azure.workloadIdentity.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dso.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dso.labels" . | nindent 4 }}
  annotations:
    {{- if and $azureWorkloadIdentityEnabled .Values.azure.workloadIdentity.clientId }}
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId | quote }}
    {{- if .Values.azure.workloadIdentity.tenantId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.workloadIdentity.tenantId | quote }}
    {{- end }}
    {{- end }}
    {{- if and (not $isESO) (eq .Values.provider "aws") .Values.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn | quote }}
    {{- end }}
    {{- if and (not $isESO) (eq .Values.provider "gcp") .Values.gcp.workloadIdentity.serviceAccount }}
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.serviceAccount | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
