run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - revive
    - contextcheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  gosec:
    severity: medium
    confidence: medium
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-naming
      - name: error-strings
      - name: receiver-naming
      - name: indent-error-flow
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
        - contextcheck
        - gosec
        - errcheck
    - path: internal/azure/servicebus\.go
      linters:
        - contextcheck

