---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dso-quantumsys-dev-v1alpha1-dynamicsecretpolicy
  failurePolicy: Fail
  name: mdynamicsecretpolicy.kb.io
  rules:
  - apiGroups:
    - dso.quantumsys.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dynamicsecretpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dso-quantumsys-dev-v1alpha1-dynamicsecretpolicy
  failurePolicy: Fail
  name: vdynamicsecretpolicy.kb.io
  rules:
  - apiGroups:
    - dso.quantumsys.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dynamicsecretpolicies
  sideEffects: None
