apiVersion: v1
kind: Secret
metadata:
  name: rollout-payment-service-db-password-initial
  namespace: default
type: Opaque
stringData:
  db-password: "initial-database-password-v1"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-active
  namespace: default
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 80
      targetPort: 5678
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-preview
  namespace: default
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 80
      targetPort: 5678
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  strategy:
    blueGreen:
      activeService: payment-service-active
      previewService: payment-service-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-api
          image: hashicorp/http-echo:latest
          args: ["-text=Payment API live with DSO managed secret\n"]
          ports:
            - containerPort: 5678
              name: http
          volumeMounts:
            - name: db-secret-volume
              mountPath: /etc/secrets
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: db-secret-volume
          secret:
            secretName: rollout-payment-service-db-password-initial
---
apiVersion: dso.quantumsys.dev/v1alpha1
kind: DynamicSecretPolicy
metadata:
  name: rollout-payment-policy
  namespace: default
spec:
  vaultRef:
    keyVaultURI: "https://my-enterprise-vault.vault.azure.net"
    objectName: "db-password"
    objectType: "Secret"
  workloadSelector:
    kind: "Rollout"
    name: "rollout-payment-service"
  targetRef:
    volumeName: "db-secret-volume"
  validationProbes:
    - type: "HTTP"
      endpoint: "http://payment-service-preview.default.svc:80/"
      expectedStatus: 200
      queryTimeout: 5
  rollbackConfig:
    autoRollback: true
    circuitBreakerThreshold: 3
