// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/quantumsys/dynamic-secret-operator/internal/probes (interfaces: ProbeExecutor)
//
// Generated by this command:
//
//	mockgen -destination=test/mocks/probes/mock_executor.go -package=mocks github.com/quantumsys/dynamic-secret-operator/internal/probes ProbeExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	secretv1alpha1 "github.com/quantumsys-dev/dynamic-secret-operator/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockProbeExecutor is a mock of ProbeExecutor interface.
type MockProbeExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockProbeExecutorMockRecorder
	isgomock struct{}
}

// MockProbeExecutorMockRecorder is the mock recorder for MockProbeExecutor.
type MockProbeExecutorMockRecorder struct {
	mock *MockProbeExecutor
}

// NewMockProbeExecutor creates a new mock instance.
func NewMockProbeExecutor(ctrl *gomock.Controller) *MockProbeExecutor {
	mock := &MockProbeExecutor{ctrl: ctrl}
	mock.recorder = &MockProbeExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbeExecutor) EXPECT() *MockProbeExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProbeExecutor) Execute(ctx context.Context, config secretv1alpha1.ValidationProbe, secretData map[string][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, config, secretData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockProbeExecutorMockRecorder) Execute(ctx, config, secretData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProbeExecutor)(nil).Execute), ctx, config, secretData)
}
